/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_NL_Ajouter_ETS (void);
GtkWidget* create_NL_Modifier_ETS (void);
GtkWidget* create_NL_Afficher_ETS (void);
GtkWidget* create_NL_Supprimer_ETS (void);
GtkWidget* create_FDaffiche (void);
GtkWidget* create_FDajoute (void);
GtkWidget* create_FDmodife (void);
GtkWidget* create_FDsupprime (void);
GtkWidget* create_FDstatistique (void);
GtkWidget* create_login (void);
GtkWidget* create_gestion (void);
GtkWidget* create_acceuil_don_rania (void);
GtkWidget* create_ajoute_don (void);
GtkWidget* create_modifer_don (void);
GtkWidget* create_supprim_don (void);
GtkWidget* create_quantite_sang (void);
GtkWidget* create_window1_ac (void);
GtkWidget* create_window2_cord (void);
GtkWidget* create_window3_tem (void);
GtkWidget* create_window4_aff (void);
GtkWidget* create_window5_sup (void);
GtkWidget* create_window6_aff2 (void);
GtkWidget* create_window_hist (void);
GtkWidget* create_Uaffiche (void);
GtkWidget* create_Uajoute (void);
GtkWidget* create_Usupprime (void);
GtkWidget* create_Ustatistique (void);
GtkWidget* create_Umodife (void);
