/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *NL_Ajouter_ETS;
  GtkWidget *NL_Modifier_ETS;
  GtkWidget *NL_Afficher_ETS;
  GtkWidget *NL_Supprimer_ETS;
  GtkWidget *FDaffiche;
  GtkWidget *FDajoute;
  GtkWidget *FDmodife;
  GtkWidget *FDsupprime;
  GtkWidget *FDstatistique;
  GtkWidget *login;
  GtkWidget *gestion;
  GtkWidget *acceuil_don_rania;
  GtkWidget *ajoute_don;
  GtkWidget *modifer_don;
  GtkWidget *supprim_don;
  GtkWidget *quantite_sang;
  GtkWidget *window1_ac;
  GtkWidget *window2_cord;
  GtkWidget *window3_tem;
  GtkWidget *window4_aff;
  GtkWidget *window5_sup;
  GtkWidget *window6_aff2;
  GtkWidget *window_hist;
  GtkWidget *Uaffiche;
  GtkWidget *Uajoute;
  GtkWidget *Usupprime;
  GtkWidget *Ustatistique;
  GtkWidget *Umodife;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 
  login = create_login ();
  gtk_widget_show (login);
 
  gtk_main ();
  return 0;
}

